# Generated by Django 5.0.1 on 2024-02-05 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp4', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, upload_to='media/product_photos/'),
        ),
    ]
